CREATE TABLE test_table (name INT, value DOUBLE);

INSERT INTO test_table (name, value) VALUES (1, rand() * 1000);
INSERT INTO test_table (name, value) VALUES (2, rand() * 2000);
INSERT INTO test_table (name, value) VALUES (2, rand() * 2000);
INSERT INTO test_table (name, value) VALUES (3, rand() * 3000);
INSERT INTO test_table (name, value) VALUES (3, rand() * 3000);
INSERT INTO test_table (name, value) VALUES (3, rand() * 3000);
INSERT INTO test_table (name, value) VALUES (4, rand() * 4000);
INSERT INTO test_table (name, value) VALUES (4, rand() * 4000);
INSERT INTO test_table (name, value) VALUES (4, rand() * 4000);
INSERT INTO test_table (name, value) VALUES (4, rand() * 4000);
INSERT INTO test_table (name, value) VALUES (5, rand() * 5000);
INSERT INTO test_table (name, value) VALUES (5, rand() * 5000);
INSERT INTO test_table (name, value) VALUES (5, rand() * 5000);
INSERT INTO test_table (name, value) VALUES (5, rand() * 5000);
INSERT INTO test_table (name, value) VALUES (5, rand() * 5000);

INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
INSERT IGNORE INTO test_table (name, value) SELECT name, value * rand() * 2 FROM test_table;
