site_name: VerdictDB Documentation
site_url: 'https://docs.verdictdb.org/'

copyright: 'Copyright &copy; 2018 The University of Michigan'

# Pages
nav:
  - Home: index.md
  - Tutorial:
    - Quickstart: documentation/quickstart/quickstart.md
        # - Python Quickstart: documentation/quickstart/quickstart_python.md
        # - Java Quickstart: documentation/quickstart/quickstart_java.md
    - Step-by-step Tutorial:
      - Simple Application: documentation/step_by_step_tutorial/step_by_step.md
      - TPC-H Application:
        - Setup Databases: documentation/step_by_step_tutorial/setup.md
        - Load TPC-H Data: documentation/step_by_step_tutorial/tpch_load_data.md
        - Example VerdictDB Application with TPC-H: documentation/step_by_step_tutorial/verdictdb_ex.md
        # - Python Step-by-step Tutorial: documentation/step_by_step_tutorial/step_by_step_python.md
        # - Java Step-by-step Tutorial: documentation/step_by_step_tutorial/step_by_step_java.md
    - Connecting to Databases: documentation/connecting_to_databases/connecting.md
        # - Python Connection: documentation/connecting_to_databases/connecting_python.md
        # - Java Connection: documentation/connecting_to_databases/connecting_java.md
  # - Getting Started:
  #   - Quickstart: getting_started/quickstart.md
  #   - Download / Install: getting_started/install.md
  #   - What's More: getting_started/whatsmore.md
  #   # - Result Structure: getting_started/results.md
  # - Tutorial:
  #   - Setup Databases (optional):
  #     - MySQL: tutorial/setup/mysql.md
  #     - Apache Spark: tutorial/setup/spark.md
  #   # - Load TPC-H Data: tutorial/tpch.md
  #   - Example VerdictDB App:
  #     - MySQL: tutorial/examples/mysql.md
  #     - Apache Spark: tutorial/examples/spark.md
  #   # - ML-based Analytics: tutorial/advanced.md

  - Reference:
    - Query Syntax:
      # - Connecting to Databases: reference/connection.md
      - VerdictDB JDBC Properties: reference/properties.md
      # - Simple Querying: reference/querying.md
      - Creating/Viewing Scrambles: reference/scrambling.md
      - Appending Scrambles: reference/append_scrambling.md
      - Dropping Scrambles: reference/drop_scrambling.md
      # - Scrambles:
      #   - What is a Scramble?: reference/what_is_scramble.md
      #   -
      - Select-Query Syntax: reference/query_syntax.md
      - Stream Querying: reference/streaming.md
    - Setting up TPC-H dataset: tutorial/tpch.md
    - Javadoc: reference/javadoc.md
    - PyVerdict Doc: reference/pyverdict.md
  - How it works:
    - Basics: how_it_works/basics.md
    - Architecture: how_it_works/architecture.md
    - Query Processing: how_it_works/query_processing.md
  #   - VerdictDB Queries: reference/supported_queries.md

# Appearance
theme:
  name: 'material'
  font:
    text: Open Sans
    code: Inconsolata
  palette:
    primary: 'Deep Purple'
    accent: 'Deep Purple'
  feature:
    tabs: true
  logo: 'images/verdictdb-logo-icon.png'
  favicon: 'images/verdictdb-favicon.png'
repo_name: 'mozafari/verdictdb'
repo_url: 'https://github.com/mozafari/verdictdb'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascripts/extra.js'

plugins:
  - search
  - markdownextradata

extra:
  verdictdb:
    version: 0.5.8


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
